house/base/urls.py
from django.urls import path

from .views import homepage, detail, housedetail, getdivarhouse

urlpatterns = [
    path('', homepage, name='homepage'),
    path('housedetails/', housedetail, name='housedetail'),
    path('housedetail/v/<str:title>/<str:token>', detail, name='detail'),
    path('gethouse/', getdivarhouse, name='getdivarhouse'),
    
]

house/house/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace='base')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

house/base/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status
import requests
from bs4 import BeautifulSoup
import json
from selenium import webdriver


def homepage(request):
    return render(request, 'home.html')

def detail(request,title,token):
    ctx = {}
    ctx['house_url'] = "/v/"+title+"/"+token
    return render(request, 'detail.html', ctx)
     

@ api_view(['GET'])
def housedetail(request):
    url = request.GET.get('url')
    if url:
        return Response(gethousedetail(url),status=status.HTTP_200_OK)
    else:
        return Response({
            'status': False,
            'detail': 'ادرس پیدا نشد.'
        })

def gethousedetail(url):
    baseurl = 'https://divar.ir'
    house = requests.get(baseurl+url)
    soup = BeautifulSoup(house.text, 'html.parser')
    image=soup.find_all(class_='kt-image-block')
    y=[]
    z = {
        "description":soup.find(class_='kt-description-row__text--primary').string,
        "title":soup.find(class_='kt-page-title__title--responsive-sized').string,
        "subtitle":soup.find(class_='kt-page-title__subtitle--responsive-sized').string,
        "price":soup.find(class_='kt-unexpandable-row__value').string,
        "user":soup.find_all(class_='kt-unexpandable-row__value')[1].string,
        "phone":soup.find(class_='kt-unexpandable-row__action kt-text-truncate ltr').string,
    }
    y.append(z)
    for elm in image:
        x={
            "images":elm.find('img')['src'],
        }
        y.append(x) 
    return y

def gethouses(price,size,rooms,building_age,floor,user_type):
    baseurl = 'https://divar.ir/s/tehran/buy-apartment/shahrak-gharb?'
    house = requests.get(baseurl+"price="+str(price)+"&size="+str(size)+"&rooms="+str(rooms)+"&building-age="+str(building_age)+"&floor="+str(floor)+"&user_type="+str(user_type))
    soup = BeautifulSoup(house.text, 'html.parser')
    content = soup.find_all(class_='kt-post-card--bordered')
    y = []
    for elm in content:
        x = {
            "title":elm.find(class_='kt-post-card__title').string,
            "publish":elm.find(class_='kt-text-truncate').string,
            "price":elm.find(class_='kt-post-card__top-description').string,
            "image":elm.find('img')['src'],
            "url":elm['href'],
        }
        y.append(x) 
    return y    

@ api_view(['GET'])
def getdivarhouse(request):
    size = request.GET.get('size')
    price = request.GET.get('price')
    building_age = request.GET.get('building_age')
    rooms = request.GET.get('rooms')
    floor = request.GET.get('floor')
    user_type = request.GET.get('user_type')
    return Response(gethouses(price,size,rooms,building_age,floor,user_type),status=status.HTTP_200_OK)
    

house/base/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <title>House</title>
</head>

<body>

  {% block nav %}

  <nav class="navbar navbar-expand-lg navbar-light bg-white m-2">
    <a class="navbar-brand" href="{% url 'base:homepage' %}"><img width="70" src="{% static 'img/32.png' %}" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white btn btn-primary m-1" href="{% url 'base:homepage' %}"><i class="fa fa-home ml-1"></i>خانه</a>
        </li>
      </ul>
    </div>
  </nav>
  {% endblock nav %}

  {% block content %}{% endblock content %}
















  {% block footer %}
  

  <div class="footer mt-3 border-top" style="background-color: white;">
    <div class="container">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-3 text-center p-2 mt-5">
            <!-- <p>تلفن تماس: 6415</p>
            <p>ادرس: ستارخان جنب پمپ بنزین ...</p> -->
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">بازگشن کالا</a></div>
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">سوالات متداول</a></div>
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">فرصت های شغلی</a></div>
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">راهنمای خرید</a></div>
          </div>
          <div class="col-md-3 text-center p-2 mt-5">
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">مرکز پشتیبانی: 6415</a></div>
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">دفتر مرکزی: تهران-ستارخان-
                شهراارا...</a></div>
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">فرصت های شغلی</a></div>
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">ساعات کاری: از شنبه الی چهارشنبه
                از ساعت8.00 الی 16.00</a></div>
          </div>
          <div class="col-md-3 text-center p-2">
            <h4 class="text-center">STORE</h4>
            <p class="text-secondary">فروشگاه store از سال 1376 شروع به کار کرده و خیلی بد کار کرده و الان تازه داره
              درست میشه</p>
          </div>
          <div class="col-md-3 text-center p-2 mt-5">
            <a href="#" class="fa fa-facebook social p-2 text-white mt-2"></a>
            <a href="#" class="fa fa-twitter social p-2 text-white mt-2" style="background-color: #55ACEE;"></a>
            <a href="#" class="fa fa-youtube social p-2 text-white mt-2" style="background-color: #bb0000;"></a>
            <a href="#" class="fa fa-instagram social p-2 text-white mt-2" style="background-color: #C12B2B;"></a>
            <a href="#" class="fa fa-facebook social p-2 text-white mt-2"></a>
            <a href="#" class="fa fa-twitter social p-2 text-white mt-2" style="background-color: #55ACEE;"></a>
            <a href="#" class="fa fa-youtube social p-2 text-white mt-2" style="background-color: #bb0000;"></a>
            <a href="#" class="fa fa-instagram social p-2 text-white mt-2" style="background-color: #C12B2B;"></a>
            <a href="#" class="fa fa-facebook social p-2 text-white mt-2"></a>
            <a href="#" class="fa fa-twitter social p-2 text-white mt-2" style="background-color: #55ACEE;"></a>
            <a href="#" class="fa fa-youtube social p-2 text-white mt-2" style="background-color: #bb0000;"></a>
            <a href="#" class="fa fa-instagram social p-2 text-white mt-2" style="background-color: #C12B2B;"></a>

          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock footer %}






  {% block js %}
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/5a32a1eab1.js"></script>
  <script>



  </script>

  {% endblock js %}
</body>

</html>

house/base/templates/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="border bg-white">
                <div class="p-1">
                    <img id="primary_image" src="" class="w-100 p-2 border-bottom" alt="">
                </div>
                <div id="images" class="row pr-4 pl-3 pt-1 pb-2">
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="border bg-white">
                <div id="title" class="m-1 p-2"></div>
                <div id="subtitle" class="m-1 p-2 text-secondary border-bottom" style="font-size:13px;"></div>
                <div class="m-2 p-2">
                    <button type="button" class="btn btn-danger phonedisplay">اطلاعات تماس</button>
                    <span class="border border-danger p-2 mr-3 text-danger" style="display: none;" id="phone"></span>
                    <div id="description" class="p-2 m-1" style="font-size:13px;"></div>
                    <!-- <div class="border-bottom p-2 mt-3">
                        <div class="d-inline pr-5">اگهی دهنده</div>
                        <div id="advetiser" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="border-bottom p-2">
                        <div class="d-inline pr-5">دسته بندی</div>
                        <div id="category" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="border-bottom p-2">
                        <div class="d-inline pr-5">محله</div>
                        <div id="location" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="border-bottom p-2">
                        <div class="d-inline pr-5">متراژ</div>
                        <div id="size" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="border-bottom p-2">
                        <div class="d-inline pr-5">سن بنا</div>
                        <div id="biuliding_age" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="border-bottom p-2">
                        <div class="d-inline pr-5">تعداد اوتاق</div>
                        <div id="number_room" class="d-inline pl-5" style="float:left;"></div>
                    </div> -->
                    <div class="border-bottom p-2">
                        <div class="d-inline pr-5">قیمت</div>
                        <div id="price" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="p-2">
                        <div class="d-inline pr-5">اگهی دهنده</div>
                        <div id="user" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="text-left mt-5">
                        <button id="share" type="button" data-content="کپی شد" data-placement="top" class="btn btn-outline-primary"><i
                                class="fa fa-share-alt text-center"></i></button>
                        <button id="bookmark" type="button" class="btn btn-outline-primary"><i class="fa fa-bookmark-o"
                                id="book"></i></button>
                    </div>

                </div>

            </div>
        </div>

    </div>
</div>




{% endblock content %}
{% block js %}
{{ block.super }}


<script>
    $.ajax({
        url: "{% url 'base:housedetail' %}?url={{house_url}}",
        type: "GET",
        success: function (data) {
            if (data) {
                $('#title').append(data[0]['title']);
                $('#subtitle').append(data[0]['subtitle']);
                $('#description').append(data[0]['description']);
                $('#primary_image').attr('src', data[1]['images']);
                $('#price').append(data[0]['price']);
                $('#user').append(data[0]['user']);
                $('#phone').append(data[0]['phone']);
                $.each(data, function () {
                    html = `
                    <img id="${$(this)[0]['id']}" src="${$(this)[0]['image']}" class="p-2 m-1 img-thumbnail const img-${$(this)[0]['id']}" alt="" style="width: 30%;">`
                    $('#images').append(html);
                });
                $(".const").click(function () {
                    $(".const").removeClass('imgborder');
                    $(".img-" + $(this).attr('id')).addClass('imgborder');
                    $('#primary_image').attr('src', $(".img-" + $(this).attr('id')).attr('src'));
                    $(".img-" + $(this).attr('id')).attr('src', $('#primary_image').attr('src'));
                });
            }
        },
        error: function (jqXHR, textStatus, errorThrown) {
            console.log(jqXHR);
            console.log(textStatus);
            console.log(errorThrown);
        }
    });
    
    $('#share').on('click', function (event) {
        event.preventDefault();
        var url = window.location.href;
        var urls = document.createElement("input");
        urls.setAttribute("value", url);
        document.body.appendChild(urls);
        urls.select();
        document.execCommand("copy");
        document.body.removeChild(urls);
        $('#share').popover('show');
        setTimeout(function () {
            $('#share').popover('hide');
        }, 1000);
    });
    $(".phonedisplay").click(function(event){
        event.preventDefault();
    $("#phone").fadeToggle();
  });

</script>

{% endblock js %}

house/base/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div class="border bg-white m-2 p-3">
                <div class="p-1 m-1 border-bottom bg-light" style="font-size: 13px;"><i
                    class="fa fa-filter ml-1"></i>فیلتر بندی
                </div>


                <div class="p-1 m-1 border-bottom" style="font-size: 13px;">متراژ</div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text bg-info text-white">از</span>
                    </div>
                    <input id="size1" type="text" placeholder="-" class="form-control"
                    aria-label="Amount (to the nearest dollar)">
                    <div class="input-group-append">
                        <span class="input-group-text bg-info text-white">متر</span>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text bg-info text-white">تا</span>
                    </div>
                    <input id="size2" placeholder="-" type="text" class="form-control"
                    aria-label="Amount (to the nearest dollar)">
                    <div class="input-group-append">
                        <span class="input-group-text bg-info text-white">متر</span>
                    </div>
                </div>




                <div class="p-1 m-1 border-bottom" style="font-size: 13px;">قیمت</div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text bg-info text-white">از</span>
                    </div>
                    <input id="price1" type="text" placeholder="-" class="form-control"
                    aria-label="Amount (to the nearest dollar)">
                    <div class="input-group-append">
                        <span class="input-group-text bg-info text-white">تومان</span>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text bg-info text-white">تا</span>
                    </div>
                    <input id="price2" type="text" placeholder="-" class="form-control"
                    aria-label="Amount (to the nearest dollar)">
                    <div class="input-group-append">
                        <span class="input-group-text bg-info text-white">تومان</span>
                    </div>
                </div>

                <div class="p-1 m-1 border-bottom" style="font-size: 13px;">سن بنا</div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text bg-info text-white">از</span>
                    </div>
                    <input id="building_age1" placeholder="-" type="text" class="form-control"
                    aria-label="Amount (to the nearest dollar)">
                    <div class="input-group-append">
                        <span class="input-group-text bg-info text-white">سال</span>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text bg-info text-white">تا</span>
                    </div>
                    <input id="building_age2" placeholder="-" type="text" class="form-control"
                    aria-label="Amount (to the nearest dollar)">
                    <div class="input-group-append">
                        <span class="input-group-text bg-info text-white">سال</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlSelect1" style="font-size: 13px;">طبقه</label>
                    <select class="form-control" id="floor">
                        <option value="">انتخاب ...</option>
                        <option value="Z">زیر هم کف</option>
                        <option value="H">هم کف</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlSelect1" style="font-size: 13px;">اگهی دهنده</label>
                    <select class="form-control" id="Advertiser">
                        <option value="">انتخاب ...</option>
                        <option value="S">شخصی</option>
                        <option value="A">املاک</option>
                    </select>
                </div>


                <div class="form-group">
                    <label for="exampleFormControlSelect1" style="font-size: 13px;">تعداد اوتاق</label>
                    <select class="form-control" id="number_of_rooms">
                        <option value="">انتخاب ...</option>
                        <option value="0">0</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </div>


                <button id="filter" type="button" class="btn btn-outline-primary btn-block mt-2" style="font-size: 14px;">اعمال فیلتر</button>


            </div>
        </div>
        <div class="col-md-9">
            <div class="border bg-white m-2 p-1">
                <div class="p-2 m-1 border-bottom">
                    <span class="text-dark" style="font-size: 13px;"><i
                        class='fas fa-sort-amount-down-alt ml-2 text-secondary' style='font-size:18px'></i>مرتب سازی
                    بر اساس: </span>
                    <span><a class="btn btn-light orderdes" id="price" style="font-size: 13px;">گران ترین</a></span>
                    <span><a class="btn btn-light orderAsc" id="price" style="font-size: 13px;">ارزان ترین</a></span>
                    <span><a class="btn btn-light orderdes" id="publish_date" style="font-size: 13px;">قدیمی
                    ترین</a></span>
                    <span><a class="btn btn-light orderAsc" id="publish_date" style="font-size: 13px;">جدید
                    ترین</a></span>
                </div>
                <div id="adver" class="row">
                </div> 
            </div>
        </div>
    </div>
</div>



{% endblock content %}
{% block js %}
{{ block.super }}

<script>
    var price = $('#price1').val()+"-"+$('#price2').val()
    var size = $('#size1').val()+"-"+$('#size2').val()
    var building_age = $('#building_age1').val()+"-"+$('#building_age2').val()
    var rooms = $('#number_of_rooms').val()
    var user_type = $('#Advertiser').val()
    var floor = $('#floor').val()
    show(price, size, rooms, building_age, user_type, floor)
    $('#filter').on('click', function (event) {
        var price = $('#price1').val()+"-"+$('#price2').val()
        var size = $('#size1').val()+"-"+$('#size2').val()
        var building_age = $('#building_age1').val()+"-"+$('#building_age2').val()
        var rooms = $('#number_of_rooms').val()
        var user_type = $('#Advertiser').val()
        var floor = $('#floor').val()
        show(price, size, rooms, building_age, user_type, floor)
    });

    

    function show(price, size, rooms, building_age, user_type, floor) {
        $('#adver').html('');

        $.ajax({
            url: "{% url 'base:getdivarhouse' %}",
            type: "GET",
            data: {
                price:price,
                size:size,
                building_age:building_age,
                rooms:rooms,
                user_type:user_type,
                floor:floor,
            },
            success: function (data) {
                if (data) {
                    $.each(data, function () {
                        var url = "{% url 'base:detail' 123 321 %}";
                        var id = $(this)[0]['url']
                        url = url.replace('123', id.split("/")[2]);
                        url = url.replace('321', id.split("/")[3]);
                        html = `
                        <div class="col-md-4">
                        <div class="border p-2 m-1 shadow p-3 mb-5 bg-white rounded" style="border-radius:5px;min-height: 289px;">
                        <div class="p-2 text-center"> 
                        <a href="${url}">
                        <img width="220" src="${$(this)[0]['image']}" alt="">
                        </a>
                        </div>
                        <div class="text-dark p-2 m-1 text-center font-weight-bold" style="font-size:13px;"">${$(this)[0]['title']}</div>
                        <div class="border border-secondary p-1 m-1 text-secondary text-center" style="font-size:13px;border-radius:7px;">${$(this)[0]['price']}</div>
                        <div class="m-1 p-2 text-secondary text-center" style="font-size:13px;">${$(this)[0]['publish']}</div>
                        </div>
                        </div>
                        `
                        $('#adver').append(html);
                    });  
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log(jqXHR);
                console.log(textStatus);
                console.log(errorThrown);
            }
        });
    }


</script>


{% endblock js %}










<!-- <div class="row">
    <div class="col-md-4">
        <img class="p-1" height="170" width="250" src="${$(this)[0]['img']}" alt=""
            style="border-radius: 10px;">
    </div>
    <div class="col-md-4">
        <div class="text-dark p-1 font-weight-bold border-bottom">${$(this)[0]['title']}
        </div>
        <div class="border border-primary text-center text-dark p-2 m-2"
            style="font-size: 13px;border-radius: 5px;">
            <span>قیمت:</span>
            <span>${$(this)[0]['price']}</span>
        </div>
        <div class="border border-primary text-center text-dark p-2 m-2"
            style="font-size: 13px;border-radius: 5px;">
            <span>تعداد اوتاق:</span>
            <span>${$(this)[0]['numberـofـrooms']}</span>
        </div>
        <div class="border border-primary text-center text-dark p-2 m-2"
            style="font-size: 13px;border-radius: 5px;">
            <span>اگهی دهنده:</span>
            <span>${$(this)[0]['Advertiser']}</span>
        </div>
    </div>
    <div class="col-md-4">
        <div class="text-body border border-primary p-2 m-2"
            style="font-size: 13px;line-height: 2rem; border-radius: 5px;">
            ${$(this)[0]['description']}

        </div>
    </div>
    <button type="button" class="m-4 btn btn-outline-success btn-block">مشاهده اگهی</button>

</div> -->



<!-- 
function sortByKeyDesc(array, key) {
        return array.sort(function (a, b) {
            var x = a[key]; var y = b[key];
            return ((x > y) ? -1 : ((x < y) ? 1 : 0));
        });
    }
    function sortByKeyAsc(array, key) {
        return array.sort(function (a, b) {
            var x = a[key]; var y = b[key];
            return ((x < y) ? -1 : ((x > y) ? 1 : 0));
        });
    } -->